<h3><i class="fa-solid fa-basket-shopping"></i> Passer une commande</h3>

<form action="index.php?action=order" method="POST">
    <fieldset>
        <legend>Ajouter un article</legend>
        <label for="product">Sélectionnez un produit:</label>
        <select name="products" id="products">
            <option value="" disabled selected>Choisir...</option>
            <?php foreach ($products as $product) { ?>
                <option value="<?php echo $product['productCode']; ?>" data-name="<?php echo $product['productName']; ?>"><?php echo $product['productName']; ?></option>
            <?php } ?>
        </select>
        <input type="hidden" name="product_id" id="product_id" value="">
        <div id="product_details">
            <p id="product_image" style="width: 50%"></p>
            <p id="product_description"></p>
            <p id="product_price"></p>
            <p id="product_quantity">Quantité : <input type="number" name="quantity" id="quantity" min="1" max="100" value="1"></p>
            <input type="submit" id="addCart" value="Ajouter">
        </div>
    </fieldset>
</form>
<div id="cart"></div>


<script src="www/js/valid_action_commande.js"></script>
