<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Fictional Restaurant, your new favourite restaurant !">
    <title>Fictional Restaurant</title>    

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="www/css/style.css">
    <link rel="stylesheet" href="www/css/slick.css">
    <link rel="stylesheet" href="www/css/slick-theme.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    
	<!-- Polices -->
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">

   

</head>
<body>
    <header>
        <div class="container">
            <a href="index.php" class="logo">
                <img src="www/img/logo2.png" alt="Logo for Freshly Restaurant">
                <strong>Fictional Restaurant</strong>
            </a>
            <nav>
                <ul>
                    <li><a href="index.php"<?php if(empty($_GET['action']) && basename($_SERVER['PHP_SELF']) == 'index.php') {echo ' class="active"';} ?>>Home</a></li>
                    <?php if ($this->is_admin()): ?>
                        <li><a href="index.php?action=homeAdmin"<?php if(isset($_GET['action']) && $_GET['action'] == 'admin') {echo ' class="active"';} ?>>Admin</a></li>
                        <li><a class="button button-primary" href="index.php?action=adminLogout">AdminLogout</a></li>
                    <?php else: ?>
                        <li><a href="index.php?action=order"<?php if(isset($_GET['action']) && $_GET['action'] == 'order') {echo ' class="active"';} ?>>Order</a></li>
                        <li><a href="index.php?action=booking"<?php if(isset($_GET['action']) && $_GET['action'] == 'booking') {echo ' class="active"';} ?>>Booking</a></li>
                        <?php if ($this->is_connect()): ?>
                            <li><a href="index.php?action=logout">Logout</a></li>
                        <?php else: ?>
                            <li><a href="index.php?action=login"<?php if(isset($_GET['action']) && $_GET['action'] == 'login') {echo ' class="active"';} ?>>Login</a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                </ul>
            </nav>



        </div>
</header>

        <?php if(isset($_GET['message'])): ?>
            <p><?= $_GET['message'] ?> </p>
        <?php endif; ?>
        
        <?php if(isset($message)): ?>
            <p><?= $message ?> </p>
        <?php endif; ?>
        <?php require $template.".phtml" ?>
    </main>

    <footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Horaires d'ouverture</h4>
					<ul>
						<li>Lundi: Fermé</li>
						<li>Mar-Mer : 9:00 - 22:00</li>
						<li>Jeu-Ven : 9:00 - 22:00</li>
						<li>Sam-Dim : 17:00 - 22:00</li>
					</ul>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>13 rue de Marseille<br>
							Marseille,<br>
							13000, Marseille</p>
						<p>06 06 06 06 06</p>
					</address>
				</aside>
				<aside>
					<h4>Réseaux Sociaux</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
			<div class="footer">
                <ul class="link-list">
                    <li><img src="www/img/payment/visa.png" alt="Visa"></li>
                    <li><img src="www/img/payment/mastercard.png" alt="MasterCard"></li>
                    <li><img src="www/img/payment/paypal.png" alt="PayPal"></li>
                </ul>
        <p>Réalisé avec <i class="fa-solid fa-heart"></i> par Xiam C.</p>
			</div> <!-- end of .footer -->
		</div> <!-- end of .container -->
	</footer>


    <!-- JavaScript de l'application -->
    <!-- Librairie jQuery -->
        <script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

	<!-- Charger le script du plugin -->
	<script src="www/js/slick.min.js"></script>
    
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
</body>
</html>